@extends('backend.layouts.app-guest')

@section('title', 'Login')

@section('content')
    <div>
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>

      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
              <img class="dashboard-logo-text" src="{{ url('/') }}/images/abc.png">

              {!! Form::open( ['url' => ['backend/google/auth'], 'method' => 'POST', 'class' => 'form-horizontal form-label-left', 'role' => 'form']) !!}

                  <div style="display: none;">
                      <label>Your Secret Key</label>
                      <input type="text" id="secret" name="secret" placeholder="Secret key" value="<?php echo $secret; ?>" required="required" />
                      <?php if ($errors->has('secret')) { ?>
                      <br /><span class="error"><?php echo $errors->first('secret'); ?></span>
                      <?php } ?>
                  </div>

                  <?php if( !is_null($qrUrl) ){ ?>
                  <div>
                      <img src="<?php echo $qrUrl; ?>">
                  </div>
                  <?php } ?>

              @if ( $errors->count() )
                  <div class="alert alert-danger">
                      {!! implode('<br />', $errors->all()) !!}
                  </div>
              @endif
                  <div>
                      <label>Verification Code</label>
                      <input type="text" id="code" name="code" placeholder="Google Verification Code" required="required"  class="form-control" />
                      <?php if ($errors->has('code')) { ?>
                      <br /><span class="error"><?php echo $errors->first('code'); ?></span>
                      <?php } ?>
                  </div>

                  <label>
                      <input type="checkbox" id="is_trusted" name="is_trusted"  />
                      Trusted for 30 days
                  </label>
                  <br><br>


                  <?php if( !is_null($qrUrl) ){ ?>

                  <p>Downlaod Google Authenticator App on your device. Install the application and create a new account by scanning the QR code. Enter the Verification Code generated by Google App in "Verification Code" field and submit!.  </p>

                  <?php }else{ ?>

                  <p> Enter the Verification Code generated by Google Authenticator App in "Verification Code" field and submit!.  </p>

                  <?php } ?>

                  <input type="hidden" name='email' value="<?php echo $email ?>"></input>

                  <input type="hidden" name='key' value="<?php echo $key ?>"></input>

                  <div>
                      <button type="submit" class="btn btn-lg btn-success btn-block">Submit</button>
                  </div>



              {!! Form::close() !!}
                    </section>
					</div>
					</div>
					</div>
					
@endsection